### ISSUE TITLE
Add date / date series 

### ISSUE THREAD

**Issue by frank12421** [frank12421/capstone-project#17]
## Value proposition
As a user, I want to make a note of information and reminders for each location so I don't forget anything. 

## Description

![GG-Add-Date](https://github.com/frank12421/capstone-project/assets/127075930/45712e79-c828-4486-b621-2b872c6a73b0)

## Acceptance criteria

- [ ] Each location has got a button - "Termin"
- [ ] Clicking on the button opens a form
- [ ] In the head there is a button that leads back to the list.
- [ ] In the form I can select an appointment or an appointment series.
- [ ] The form area for the one-time appointment contains the selection options for the date and time, respectively, as well as a text field for a note....
- [ ] The form area for the series of appointments also contains the options for the series: Stunde, Tag, Woche, Monat.
- [ ] The form gets a "Speichern" button. 
- [ ] After clicking the button, the data will be stored in an array. 

## Tasks

- [ ] Update the location-card in the location- list
- [ ] Create a form
- [ ] Save the data in an array

Size: L

**Comment by doctype-Melvin** [comment]
Great feature!
lgtm
