### ISSUE TITLE
Show upcoming dates on HP

### ISSUE THREAD

**Issue by frank12421** [frank12421/capstone-project#19]
## Value proposition

As a user, I would like to see the upcoming dates on the homepage 
so I don't miss anything.

## Description
![US-Show-upcomming-dates](https://github.com/frank12421/capstone-project/assets/127075930/ff112fe2-b802-4846-b1e7-7477dc601ea1)

## Acceptance criteria

- [ ] The homepage shows a table with the upcoming dates.
- [ ] The table always shows the "Heute" row, even if no appointments are entered. 
- [ ] The size of the display area dynamically adapts to the content. 
- [ ] The order of the dates follows the pattern: "Heute", "Morgen", "Diese Woche", "Demnächst".
- [ ] If there is no data for one of these time periods, the display is omitted.
- [ ] A maximum of 6 data lines are visible.
- [ ] If there are more dates than space, the other dates can be scrolled. The headline "Was", "Wann", "Wo" always remains visible.
- [ ] With a click on a line the display changes to the info display. 
- [ ] The info display shows all data for this appointment. 
- [ ] The info display shows an x in the upper right corner.
- [ ] A click on the x closes the info display and switches back to the table view, no appointment is marked.

 
## Tasks

- [ ] Create a component that creates the content of the appointment view.
- [ ] Update the homepage.

Size: L

**Comment by mbosselmann** [comment]
Hi Frank,
LGTM! 🦊

**Comment by cmgoersch** [comment]
So I think everything described in your UserStorry is displayed fine. 

The creation of new appointments that then also appear on the home page I did not succeed. I think this is another of your now upcoming UserStorrys :)

What I noticed in the quality-assurance that is not apparent to the user that individual entries are clickable and thus open to learn more. Here it would be from the point of view of a user certainly helpful to hang a small button with a magnifying glass at the end of each line. Of course, the whole bar is clickable but so it would be more understandable. It can also be a calendar icon or simply more space between the lines or lines :)

Also a line above your bar with "upcoming events" would be helpful for the user for better comprehensibility.

Your button navigation is still a bit confusing. On the landing page the red and green buttons are placed at the bottom while on all subpages they are placed at the top. Also the continuous bar is still a bit difficult to recognize as a button. Also due to the fact that you use completely different button types on the "All cities" page.

Now my comments have not exactly something to do with the Acceptance criteria. So understand my comments as a suggestion and think about what you want to accept and whether it fits into your progress.

I'll give you a black check mark so that you can read my comment.

If the QA appears again as an update, I will gladly release it no matter what you have taken over.

Best regards and have fun coding. You are doing a great job.

Translated with www.DeepL.com/Translator (free version)

**Comment by frank12421** [comment]
@cmgoersch 
Thank you for the good advice. I just tested again the functionality of creating an appointment from vercel. For me it works without errors. Maybe we should have a look together. Then I can vlt. recognize where the error lies. Please still for release.
