### ISSUE TITLE
List of Plants

### ISSUE THREAD

**Issue by frank12421** [frank12421/capstone-project#2]
## Value proposition

As a user  
I would like to see all plants in a list  
So that I get an overview of all the plants.

![GG-UserStory1](https://user-images.githubusercontent.com/127075930/236118155-26b6fe6c-6ef1-4e1b-8767-be8d230bcf03.png)

## Acceptance criteria

- [ ] Each plant gets one card
- [ ] Each card gets the picture of the plant
- [ ] Each card shows the information belonging to the plant, according to the scribble.
- [ ] The list scrolls vertically
- [ ] The list is unsorted

## Tasks

- [ ] create a branch
- [ ] create a plant-db.js
- [ ] create a component: PlantCard.js
- [ ] create a component: ListOfPlants.js
- [ ] add basic CSS

Size: L

**Comment by mbosselmann** [comment]
Hi Frank,
you rock! :octocat: I have some remarks for you to consider:

## Description:
- you write "PlantDatum" and also "Pflanzdatum". I would decide for one language ( I know it is different to switch between different languages) 😅 
- you already show very detailed information about the different plants. But there is for example no value displayed for "Standort" sometimes. Same for other "Fruchtfarbe", "Status" etc. It would be cool to see which values the user will see.
- I am also not sure about `N.N.` Are these necessary? 🤔 If not, I would remove them.

## Acceptance criteria
- "Each card shows the information belonging to the plant, according to the scribble." - as you refer to the scribble it would be really helpful to really see the plant information in more detail in your wireframe
- "The List scroll vertically" - "the list scrolls vertically"

## Tasks
- "create a the List" - maybe you mean "create a list component"? 

And if you do not want to set a size for your user story (this is optional) then you can remove this part. With size you can decide what you think is the complexity of your user story (usually small, medium or large).

I hope this does help! Feel free to ask if you have questions. :)

**Comment by frank12421** [comment]
Thank you Mareike for the helpful hints. I have changed the following:
Description:
- New, more concrete scribble - the app will have german as frontend language.
Acceptance criteria:
- wireframe reworked 
- typo corrected (scrolls vertical)
Tasks:
- tasks adjusted
-

**Comment by REFAEI91** [comment]
LGTM
