### ISSUE TITLE
Add DB / Show all plants in one location

### ISSUE THREAD

**Issue by frank12421** [frank12421/capstone-project#20]
## Value proposition

As a user, I want to see all the plants that are in one location. 
To get an overview of this location. 

## Description
![US-Showing-all-plants-location ](https://github.com/frank12421/capstone-project/assets/127075930/f9afcc7e-1797-4beb-9019-3340e553c3e0)

## Acceptance criteria

- [ ] The list of locations has been updated.
- [ ] The location information cannot be moved.
- [ ] The list shows a map for each plant at that location.
- [ ] The list can be scrolled.
- [ ] The button "zurück" in the header leads back to the list of all locations. 

Acceptance criteria that are no longer valid: 
- [ ] Each location has an "Alle zeigen"-button.
- [ ] Clicking on a "Show all" button opens a list for this location.
- [ ] The list shows the location information in the upper part, according to the scribble.
- [ ] Each card contains the data as seen in the scribble.

## Tasks

- [ ] Create a database that contains the plants for each site.
- [ ] Revise the list of locations.
- [ ] Create the list to display the plants for this location.

Size: L

**Comment by mzschunke** [comment]
Hi Frank, very well written US! :)
