### ISSUE TITLE
Show Dates for this Place

### ISSUE THREAD

**Issue by frank12421** [frank12421/capstone-project#23]
## Value proposition

As a user, I want to see what the deadlines are for that location  
 to see what should be taken care of. 

## Description
![US-Show-upcomming-dates-place](https://github.com/frank12421/capstone-project/assets/127075930/5e020cb6-dc43-4c9c-9156-b9a21579b837)

## Acceptance criteria

- [ ] The list for each location shows the saved appointments for this location. 
- [ ] The appointment list is only displayed if there are also appointments for this location. 
- [ ] The dates of the appointments are displayed as "Heute", "Morgen", "Diese Woche", only after that the date appears. 
- [ ] There is no header line.
- [ ] A maximum of 3 data lines are displayed.
- [ ] The list of appointments can only be scrolled up and down if there are more appointments than can be displayed.
- [ ] A click on a list entry opens the detail view.
- [ ] The detail view shows all information about this appointment except the location.
- [ ] The detail view shows an x in the upper right corner.
- [ ] Clicking on the x closes the info display and switches back to the list view, with no appointment selected.

## Tasks

- [ ] Transfer appointment management to db: enter + read out
- [ ] Revise map for displaying appointments/detail info on HP
- [ ] Include map in the list of locations

Size: M

**Comment by HenrikeStahlhut** [comment]
LGTM 🪴
