### ISSUE TITLE
A quick overview on the HP

### ISSUE THREAD

**Issue by frank12421** [frank12421/capstone-project#25]
## Value proposition

As a user, I would like to see on the HP how many plants I have in total and how many locations they are distributed to  
so I can get a quick overview. 

## Description

no image of wireframe

## Acceptance criteria

- [ ] The button "Alle Pflanzen zeigen", additionally shows the information about the number of different varieties stored in the database and the total number of all plants distributed on the sites. 
- [ ] The "Alle Standorte zeigen" button additionally shows the information about how many locations there are in total. 

## Tasks

- [ ] revise both buttons on the landing page. 

Size: M
