### ISSUE TITLE
Create new plant

### ISSUE THREAD

**Issue by frank12421** [frank12421/capstone-project#4]
## Value proposition

As a user  
I want to be able to create a new plant.  
So that the new plant is added to the list of all plants.

## Description
![GG-UserStory2](https://user-images.githubusercontent.com/127075930/235925134-837fbf4f-67a2-4e4c-bba5-1a3c0492acc6.png)

## Acceptance criteria

- [ ] The Form fields looks like the Scribble:
- Text: variety, fruit color, flavor,
- Text-area: Description (max. 200 characters)
- Number: plant height, fruit size
- Site suitability and location are both option fields:
    - Roof
    - greenhouse
    - open field
    - Planting date: input -date 
- [ ] All Fields are required
- [ ] Click on Submit adds the Plant to the List
- [ ] The form equals the a11y  

## Tasks

- [ ] create a branch
- [ ] create a component / NewPlantForm.js
- [ ] add Data to the the List
- [ ] add basic CSS
- [ ] write the tests

Size:
