### ISSUE TITLE
Plant Places

### ISSUE THREAD

**Issue by frank12421** [frank12421/capstone-project#5]
## Value proposition

As a user,  
I would like to see a list of all the locations/people for which I grow plants.  
So that I can see what locations/people there are, what conditions there are and how many plants are needed there.

## Description

![US-Plant-Places](https://user-images.githubusercontent.com/127075930/236153291-16479293-5946-4e33-b609-ac0dff6d014e.png)

## Acceptance criteria

- [x] the Plant Place Cards are displayed as a list
- [x] the list scrolls vertically
- [x] each place had his one card
- [x] each card shows a picture or a sign form the Place
- [x] each card shows all data from the db

## Tasks

- [x] create a db: PlantPlaces.js
- [x] create a component: ListOfPlaces.js
- [x] add Basic CSS

Size: M

**Comment by CJAkkuec** [comment]
> the List looks like the scribble

I think QA might have a bit of trouble checking off that acceptance criteria depending on how accurate they are required to be. I would prefer an acceptance criteria such as "Plant place cards are displayed as a list.", which leaves a little more leeway.

 > the db contains several records with the following structure:

I'd argue that's not an acceptance criteria, but a task. QA can't really (in most cases) check against your database.

 > Name: Text
 > Kapazität: Number
 > Licht: Schatten / Halbschatten / Voll
 > Standort: Gewächshaus / Dach / Freiland
 > Regenschutz: Ohne / Teilweise / Voll

If you're including an approximate database structure in your tasks, I would prefer it to be valid javascript, and I'd probably stick to one language. (See: Number vs. the rest) 👍

**Comment by frank12421** [comment]
Thank you for the good advice. 
I have implemented all and added the following:
Acceptance criteria:
- [ ] the list scrolls vertically
