### ISSUE TITLE
Add Homepage

### ISSUE THREAD

**Issue by frank12421** [frank12421/capstone-project#6]
## Value proposition

As a user, I want to see what options I have. 
So I can decide what I want to do next. 

## Description

![US-Add-Hompage](https://user-images.githubusercontent.com/127075930/236173880-2ae628ae-dad9-4caa-ba74-9da6d7de7656.png)

## Acceptance criteria

- [ ] there is a homepage with a picture in the Head.
- [ ] the homepage has 2 buttons.
- [ ] the upper button opens the page with the plant list.
- [ ] the lower button opens the page with the plant places.
- [ ] both lists are displayed on a dynamically created page
- [ ] the plant list has a button that links to the homepage.
- [ ] on the map showing a plant the border color has been changed to green
- [ ] the list of all places has a button that links to the homepage.
- [ ] on the map showing a place the border color has been changed to red.

## Tasks

- [ ] create the homepage
- [ ] add dynamic routing
- [ ] add new page to display the lists
- [ ] customize componente ListOfPlants
- [ ] customize componente ListOfPLaces
- [ ] customize the card that shows a plant
- [ ] customize the card that showing a place 

Size: L

**Comment by CJAkkuec** [comment]
If I'm understanding correctly, this isn't just about creating the Homepage, but also some routing? I would probably make that a little more clear. 🤔

**Comment by mbosselmann** [comment]
Hi Frank,
you rock! 🪨 I think you do not need to work with dynamic routing in this case as you could also use predefined paths as `places` for the plant places and `plants` for the plant list.
This is just a note for you to think about, but this does not hinder me from approving your user story. :octocat:

**Comment by Sullynobugz** [comment]
Hi Frank, unfortunately, the acceptance criterion "the plant/all places list has a button that links to the homepage" doesn't seem to be working for me. I assume the "Back" button is intended here. Additionally, the two buttons on the first page appear to be somewhat buggy. Sometimes, clicking on either one of them does not work. I tried to identify a pattern, but it seems random to me at the moment.

**Comment by frank12421** [comment]
Got it. Thanks for reviewing. Bug is fixed.
