### ISSUE TITLE
Add plant to a place

### ISSUE THREAD

**Issue by frank12421** [frank12421/capstone-project#7]
## Value proposition

As a user,  
I want to assign plants to a location.  
So that I can see how many plants are there are in totaly and how many still find a place there.

## Description

![US-Add-Plant-to-Place](https://user-images.githubusercontent.com/127075930/236412842-bd3ad310-e17b-42d8-a0d0-a746a97dc12b.png)

## Acceptance criteria

- [ ] each plant card has an add-button
- [ ] the add-button opens a plant selection list
- [ ] the plant selection list shows all plants sorted alphabetically
- [ ] each plant is displayed on a card
- [ ] the list can be scrolled vertically
- [ ] a click on the plus adds this plant to the location
- [ ] after clicking on the plus, the list of locations is displayed
- [ ] the capacity display for the selected location has decreased by one plant
- [ ] the assignment of the plant to the location is saved in the local state

## Tasks

- [ ] create a branch
- [ ] revise the map to display the location list
- [ ] consider the recalculation of the capacity
- [ ] create the map for displaying the plant list
- [ ] store the data in the local state

Size: L

**Comment by mzschunke** [comment]
Hi Frank, awesome user story! =) 

I just have a few remarks: 

**Value proposition**

I would try to make it more clear that the focus is on capacity for each location, for example like this: 

As a user,
I want to assign plants to a location
So that I can see how many plants **there are in total** and how many can still find a place there.

**Description**

Maybe it's easier to understand if you only draw one arrow from the 'add sign' location page to the plant list, and then an arrow back to the location page (from the 'plus' sign). 

I think it would be good if the cards in your wirfeframe are shown in alphabetical order, if they are intended to be displayed like this. 

**Acceptance criteria**

 _"The capacity display for the selected location has decreased by one plant"_ - If I understood it correctly, you want to add a plant to a location. That would mean that the capacity counter gets increased (+), not decreased (-).

Feel free to ask me if anything is unclear! 
Cheers, Moritz

**Comment by frank12421** [comment]
Hello Moritz, thanks for the good tips. I have implemented all but the last one. 

The capacity at a, location, means how many plants can stand there max. 

The capacity in one location decreases when I add a new plant. 
Assuming 20 plants fit there then the capacity shows:
20 / 20 

If I add a plant, the free capacity decreases by 1. So it would say: 
19 / 20

I hope it becomes clear what I mean. 
Maybe I change the display later. For the moment it should work like this.

**Comment by mzschunke** [comment]
Got you - Thanks for making it more clear!  LGTM! :)
