### ISSUE TITLE
List of all plants in one place, delete plants, add plants

### ISSUE THREAD

**Issue by frank12421** [frank12421/capstone-project#8]
## Value proposition

As a user, I want to see a list of plants that are in a location.
So that I can delete plants there or add more from an existing one.

## Description

![US-List-of-Plants-at-one-location](https://user-images.githubusercontent.com/127075930/236387134-7e7dd006-b7b0-47f7-bc3e-7ff1412a95ab.png)

## Acceptance criteria

- [ ] A click on the button "Liste anzeigen" opens a list of all plants at this location. The list is sorted alphabetically.
- [ ] The list scrolls vertically.
- [ ] The list has a button "zurück" in the head.
- [ ] Each plant has its own cart.
- [ ] Each cart has a "plus" and a "minus" button.
- [ ] A click on the "minus" button deletes this plant immediately from the list, the list is still displayed.
- [ ] A click on the "plus" button copies the cart and sorts it under the selected cart. The list is still displayed.
- [ ] A click on the "zurück" button closes the list of all plants at this location and opens the list of all locations.
- [ ] The data has been saved to the local Stage.
- [ ] The capacity for this location has been updated.  

Added after the update of the UserStory:

- [ ] The list contains a fixed header
- [ ] The header contains a fixed card with information about the capacity at this location.

## Tasks

- [ ] Create a branch
- [ ] Edit the cart that displays one location
- [ ] Expand the card component to show all the different versions 
- [ ] Create the card version that shows one plant per location and contains the buttons
- [ ] Update the data in the local state

Size: L

**Comment by HenrikeStahlhut** [comment]
Nice work, looks good to me ⚡️

**Comment by frank12421** [comment]
The user story was customized because it became apparent during the development process that an overview of the location in this list was needed. I have added the adapted scribble to the PR. 

![Image](https://github.com/frank12421/capstone-project/assets/127075930/c7be7179-f24d-4f72-b06e-b851969402ad)

The following acceptance criteria have been included:

- The list contains a fixed header
- The header contains a fixed card with information about the capacity at this location.
